resources:
  - ../_base
patches:
  - target:
      kind: Namespace
      name: replace-me
    patch: |-
      - op: replace
        path: /metadata/name
        value: web-terminal-operator
  - target:
      kind: OperatorGroup
      name: replace-me
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/name
        value: web-terminal
      - op: replace
        path: /metadata/namespace
        value: web-terminal-operator
  - target:
      kind: Subscription
      name: replace-me
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/name
        value: web-terminal
      - op: replace
        path: /metadata/namespace
        value: web-terminal-operator
      - op: replace
        path: /spec/source
        value: certified-operators
      - op: replace
        path: /spec/channel
        value: stable
      - op: replace
        path: /spec/name
        value: web-terminal
