# NOTE: This kustomization resource is not applied by ArgoCD. It is provided as an example of
# what you would include if you were managing secrets via external sources or through an encryption
# tool like sOps.
resources:
  - ../../../../components/cloud_credentials/aws
  - ../../../../components/installconfig/aws
  - ../../../../components/pull_secret
patches:
  - target:
      kind: Secret
      name: cluster-ssh-key
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cluster-team-1
  - target:
      kind: Secret
      name: ocp-pull-secret
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cluster-team-1
  - target:
      kind: Secret
      name: cloud-creds
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cluster-team-1
  - target:
      kind: Secret
      name: installconfig
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cluster-team-1
