apiVersion: v1
kind: Secret
metadata:
    name: replace-me
    namespace: openshift-gitops
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: replace-me
  sshPrivateKey: replace-me
